export enum CommerceStep {
  SEARCH_RESULTS = "SEARCH_RESULTS",
  PRODUCT_DETAIL = "PRODUCT_DETAIL",
  CART_REVIEW = "CART_REVIEW",
  CHECKOUT_CONFIRM = "CHECKOUT_CONFIRM",
  ORDER_COMPLETE = "ORDER_COMPLETE"
}
